# Generated by Django 5.0 on 2023-12-12 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value must be greater than or equal to 0.')])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(editable=False)),
                ('phone_number', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('reference_point', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('comments', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('total_amount', models.DecimalField(decimal_places=5, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('delivery_cost', models.IntegerField(default=150, editable=False)),
                ('ordered_products', models.TextField(editable=False)),
                ('products', models.ManyToManyField(to='ecoMarketAPI.orderitem')),
            ],
        ),
    ]
