# Generated by Django 5.0 on 2023-12-13 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoMarketAPI', '0002_productcategory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField()
        ),
    ]
