# Generated by Django 5.0 on 2023-12-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoMarketAPI', '0006_alter_productcategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
