# Generated by Django 5.0 on 2023-12-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoMarketAPI', '0014_order_total_amount_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_products',
            field=models.JSONField(default=list, editable=False),
        ),
    ]
