# Generated by Django 5.0 on 2023-12-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoMarketAPI', '0015_alter_order_ordered_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_products',
            new_name='ordered_product_list',
        ),
    ]
