# Generated by Django 5.0 on 2023-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoMarketAPI', '0016_rename_ordered_products_order_ordered_product_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
